sudo: required
language: cpp
os: linux

compiler:
  - clang
  - gcc

env:
  - QT="551"
  - QT="562"
  - QT="571"
  - QT="58"
  - QT="591"

install:
  - sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
  - sudo apt-add-repository -y "ppa:beineri/opt-qt${QT}-trusty"
  - sudo apt-get -qq update
  - sudo apt-get install "qt${QT:0:2}base" "qt${QT:0:2}tools" "qt${QT:0:2}canvas3d" "qt${QT:0:2}svg"

before_script:
  - /opt/qt${QT:0:2}/bin/qmake --version

script:
  - /opt/qt${QT:0:2}/bin/qmake src/GrafOntoConsole.pro
  - make
  - /opt/qt${QT:0:2}/bin/qmake src/GrafOntoGui.pro
  - make
  - ./grafonto -demo -auto

notifications:
  slack:
    secure: "yT4ZGDOtEfblsyjvjv9iF0uaevkWw5fe6ATVHJ2wlggqMv8DQmmiReMR/g+M6E7tt81klc2gfTE8kofWgMOYuyE5QbH7XhCto8lhYG4G3rcjrncy8NMK4XzVmMXclRKknhkK7D0CcmelRe8LeKeh+zk/tOD7dQ0uLtuSnDJJZZ9X/IhiSEeckicUI6jvQY4B49PIGP/rQmFbRyC1fRVPundHuZiZrr9NpQRRfdWyPGXYh5coNx2/7POBT2fdS9vUvqm6hx1d0C9xSbqca8Pk4nNF/N1JnrbwsFb4gZpNszkZp6cwiSjx0hmiHoUegKs1yU6oiS0pGHCnaBU0VDNJLgKjJZ9322cgEAsVDIThbL6VQFk7KR9ikZj7Aw6PyoQJziggi+G2RzReWAA5IU3FZmoHnkSg+XZqPLlzlODQl/pm9YIrVO6lmWy6KvhSJUFhPYkuHgiu0TaaIqEnLPJm5Ayc8ehO745XPL0luNdOXpPIojEbkERFhtQlajLYPm5Y8GHFpJrt9qhwkt5H7bYI39uD9653y2L9sqIAYWnQ5cgEvsw6PuemMAMckjkH6fVubxxDCFssXaMYID6XEYhm+oJMP+MUhBCDIWXnMgb1xWf5MSPcKnUX2qVPRCiynv3XKsbY0keU9Tfqj4aamjhcqxQLop2jvUu4ZCZgsacJXE4="
  email: false
