sudo: required
language: cpp
os:
  - linux
#  - osx

compiler:
#  - clang
  - gcc

install:
  - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository -y ppa:beineri/opt-qt562
#  - sudo apt-add-repository -y ppa:beineri/opt-qt58-trusty
  - sudo apt-get -qq update
  - sudo apt-get install qt56base qt56tools qt56canvas3d qt56svg
#  - sudo apt-get install qt58base qt58tools

before_script:
  - /opt/qt56/bin/qmake --version

script:
  - /opt/qt56/bin/qmake src/GrafOntoConsole.pro
  - make
  - /opt/qt56/bin/qmake src/GrafOntoGui.pro
  - make

notifications:
  slack:
    secure: "yT4ZGDOtEfblsyjvjv9iF0uaevkWw5fe6ATVHJ2wlggqMv8DQmmiReMR/g+M6E7tt81klc2gfTE8kofWgMOYuyE5QbH7XhCto8lhYG4G3rcjrncy8NMK4XzVmMXclRKknhkK7D0CcmelRe8LeKeh+zk/tOD7dQ0uLtuSnDJJZZ9X/IhiSEeckicUI6jvQY4B49PIGP/rQmFbRyC1fRVPundHuZiZrr9NpQRRfdWyPGXYh5coNx2/7POBT2fdS9vUvqm6hx1d0C9xSbqca8Pk4nNF/N1JnrbwsFb4gZpNszkZp6cwiSjx0hmiHoUegKs1yU6oiS0pGHCnaBU0VDNJLgKjJZ9322cgEAsVDIThbL6VQFk7KR9ikZj7Aw6PyoQJziggi+G2RzReWAA5IU3FZmoHnkSg+XZqPLlzlODQl/pm9YIrVO6lmWy6KvhSJUFhPYkuHgiu0TaaIqEnLPJm5Ayc8ehO745XPL0luNdOXpPIojEbkERFhtQlajLYPm5Y8GHFpJrt9qhwkt5H7bYI39uD9653y2L9sqIAYWnQ5cgEvsw6PuemMAMckjkH6fVubxxDCFssXaMYID6XEYhm+oJMP+MUhBCDIWXnMgb1xWf5MSPcKnUX2qVPRCiynv3XKsbY0keU9Tfqj4aamjhcqxQLop2jvUu4ZCZgsacJXE4="
