version: "{build}"

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      QT: "5.6"
      PLATFORM: "x86"
      QTCOMPILER: "msvc2015"
      VS: "14"
      QTMAKE: "nmake"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      QT: "5.6"
      PLATFORM: "x64"
      QTCOMPILER: "msvc2015_64"
      VS: "14"
      QTMAKE: "nmake"

init:
  - ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VS" + "0COMNTOOLS"))
  - set QTDIR=C:\Qt\%QT%\%QTCOMPILER%
  - set PATH=%PATH%;%QTDIR%\bin
  - if "%QTMAKE%" == "mingw32-make" set PATH=%PATH%;C:\MinGW\bin
  - if "%QTMAKE%" == "nmake" if "%PLATFORM%" == "x64" "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - if "%QTMAKE%" == "nmake" if "%PLATFORM%" == "x86" call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat"
  - if "%QTMAKE%" == "nmake" if "%PLATFORM%" == "x64" call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64

build_script:
  - qmake src\GrafOntoConsole.pro
  - cmd: "%QTMAKE%"
  - qmake src\GrafOntoGui.pro
  - cmd: "%QTMAKE%"

test_script:
  - release\grafonto.exe -demo -auto
